Feature/map
cmu-sei/Vm.Api pull request #1
Opened 2020-10-12 14:22 UTC by sei-ebram

2020-10-27 17:16 UTC, sei-chershberger approved these changes

2020-10-27 17:28 UTC, sei-tspencer approved these changes

2020-11-04 15:07 UTC, sei-aschlackman requested changes

2020-11-04 15:07 UTC, sei-aschlackman commented on src/Player.Vm.Api/Features/Vms/VmService.cs
> +        {
This method needs a permissions check doesn't it?

2020-11-04 15:07 UTC, sei-aschlackman commented on src/Player.Vm.Api/Features/Vms/VmService.cs
> +        public async Task<bool> DeleteMapAsync(Guid mapId, CancellationToken ct)
Permissions check needed here too.

2020-11-05 15:28 UTC, sei-aschlackman approved these changes

2020-11-05 15:40 UTC, sei-ebram commented
Initial implementation of Map feature

2020-11-05 15:40 UTC, merged