map improvements
cmu-sei/Vm.Api pull request #5
Opened 2020-11-12 17:22 UTC by sei-byoung

Small changes and fixes to map application backend.

2020-11-12 21:13 UTC, sei-aschlackman requested changes

2020-11-12 21:13 UTC, sei-aschlackman commented on src/Player.Vm.Api/Features/Vms/VmService.cs
> +                if ((await _playerService.CanAccessTeamsAsync(m.TeamIds, ct) || m.TeamIds.Count == 0))
I think this reads that if the map has no team assigned to it, anyone in the system can access the map? Probably need to check CanManage on the user's primary team in this view if there are no teams assigned.

2020-11-17 13:52 UTC, sei-byoung commented on src/Player.Vm.Api/Features/Vms/VmService.cs
> -            if (!formTeams.Any())
That wasn't supposed to have been removed. I've added it back

2020-11-24 16:25 UTC, sei-aschlackman approved these changes

2020-12-01 16:03 UTC, sei-ebram approved these changes

2020-12-07 15:44 UTC, sei-tspencer approved these changes

2020-12-10 14:43 UTC, sei-noconnor approved these changes

2020-12-10 14:56 UTC, merged